# Generated by Django 2.2.7 on 2019-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('appt_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('node_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('private_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
