# Generated by Django 2.2.7 on 2019-11-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='node_number',
            new_name='node_id',
        ),
    ]
