# Generated by Django 2.2.7 on 2019-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuity', '0002_auto_20191122_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
    ]
