# Generated by Django 2.2.7 on 2019-12-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuity', '0003_auto_20191123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='request_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='node_id',
            field=models.IntegerField(null=True),
        ),
    ]
