# Generated by Django 2.2.7 on 2019-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuity', '0004_auto_20191209_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='confirmation_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
